default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: 
  # password: 
  username: <%= ENV['PG_USERNAME']%>
  password: <%= ENV['PG_PASSWORD']%>

development:
  <<: *default
  database: asana_development
  host: 

test:
  <<: *default
  database: asana_test

production:
  <<: *default
  database: asana_production
  username: asana
  password: <%= ENV['ASANA_DATABASE_PASSWORD'] %>
