default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: asana_development
test:
  <<: *default
  database: asana_test

production:
  <<: *default
  database: asana_production
  username: asana
  password: <%= ENV['ASANA_DATABASE_PASSWORD'] %>
